// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userService.proto

package userService

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// AuthUser
type RpcAuthUserRequest struct {
	UserDirectory        string   `protobuf:"bytes,1,opt,name=userDirectory,proto3" json:"userDirectory,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcAuthUserRequest) Reset()         { *m = RpcAuthUserRequest{} }
func (m *RpcAuthUserRequest) String() string { return proto.CompactTextString(m) }
func (*RpcAuthUserRequest) ProtoMessage()    {}
func (*RpcAuthUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_874b4b11a4ddc7c4, []int{0}
}

func (m *RpcAuthUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcAuthUserRequest.Unmarshal(m, b)
}
func (m *RpcAuthUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcAuthUserRequest.Marshal(b, m, deterministic)
}
func (m *RpcAuthUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcAuthUserRequest.Merge(m, src)
}
func (m *RpcAuthUserRequest) XXX_Size() int {
	return xxx_messageInfo_RpcAuthUserRequest.Size(m)
}
func (m *RpcAuthUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcAuthUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RpcAuthUserRequest proto.InternalMessageInfo

func (m *RpcAuthUserRequest) GetUserDirectory() string {
	if m != nil {
		return m.UserDirectory
	}
	return ""
}

func (m *RpcAuthUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RpcAuthUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RpcAuthUserResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	AuthToken            string   `protobuf:"bytes,2,opt,name=authToken,proto3" json:"authToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcAuthUserResponse) Reset()         { *m = RpcAuthUserResponse{} }
func (m *RpcAuthUserResponse) String() string { return proto.CompactTextString(m) }
func (*RpcAuthUserResponse) ProtoMessage()    {}
func (*RpcAuthUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_874b4b11a4ddc7c4, []int{1}
}

func (m *RpcAuthUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcAuthUserResponse.Unmarshal(m, b)
}
func (m *RpcAuthUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcAuthUserResponse.Marshal(b, m, deterministic)
}
func (m *RpcAuthUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcAuthUserResponse.Merge(m, src)
}
func (m *RpcAuthUserResponse) XXX_Size() int {
	return xxx_messageInfo_RpcAuthUserResponse.Size(m)
}
func (m *RpcAuthUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcAuthUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RpcAuthUserResponse proto.InternalMessageInfo

func (m *RpcAuthUserResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *RpcAuthUserResponse) GetAuthToken() string {
	if m != nil {
		return m.AuthToken
	}
	return ""
}

// CreateUser
type RpcCreateUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	UserDirectoryId      string   `protobuf:"bytes,2,opt,name=userDirectoryId,proto3" json:"userDirectoryId,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	EmployeeId           string   `protobuf:"bytes,4,opt,name=employeeId,proto3" json:"employeeId,omitempty"`
	GroupId              string   `protobuf:"bytes,5,opt,name=groupId,proto3" json:"groupId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcCreateUserRequest) Reset()         { *m = RpcCreateUserRequest{} }
func (m *RpcCreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*RpcCreateUserRequest) ProtoMessage()    {}
func (*RpcCreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_874b4b11a4ddc7c4, []int{2}
}

func (m *RpcCreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcCreateUserRequest.Unmarshal(m, b)
}
func (m *RpcCreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcCreateUserRequest.Marshal(b, m, deterministic)
}
func (m *RpcCreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcCreateUserRequest.Merge(m, src)
}
func (m *RpcCreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_RpcCreateUserRequest.Size(m)
}
func (m *RpcCreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcCreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RpcCreateUserRequest proto.InternalMessageInfo

func (m *RpcCreateUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RpcCreateUserRequest) GetUserDirectoryId() string {
	if m != nil {
		return m.UserDirectoryId
	}
	return ""
}

func (m *RpcCreateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RpcCreateUserRequest) GetEmployeeId() string {
	if m != nil {
		return m.EmployeeId
	}
	return ""
}

func (m *RpcCreateUserRequest) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

type RpcCreateUserResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcCreateUserResponse) Reset()         { *m = RpcCreateUserResponse{} }
func (m *RpcCreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*RpcCreateUserResponse) ProtoMessage()    {}
func (*RpcCreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_874b4b11a4ddc7c4, []int{3}
}

func (m *RpcCreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcCreateUserResponse.Unmarshal(m, b)
}
func (m *RpcCreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcCreateUserResponse.Marshal(b, m, deterministic)
}
func (m *RpcCreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcCreateUserResponse.Merge(m, src)
}
func (m *RpcCreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_RpcCreateUserResponse.Size(m)
}
func (m *RpcCreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcCreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RpcCreateUserResponse proto.InternalMessageInfo

func (m *RpcCreateUserResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

// 删除用户
type RpcDeleteUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcDeleteUserRequest) Reset()         { *m = RpcDeleteUserRequest{} }
func (m *RpcDeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*RpcDeleteUserRequest) ProtoMessage()    {}
func (*RpcDeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_874b4b11a4ddc7c4, []int{4}
}

func (m *RpcDeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcDeleteUserRequest.Unmarshal(m, b)
}
func (m *RpcDeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcDeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *RpcDeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcDeleteUserRequest.Merge(m, src)
}
func (m *RpcDeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_RpcDeleteUserRequest.Size(m)
}
func (m *RpcDeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcDeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RpcDeleteUserRequest proto.InternalMessageInfo

func (m *RpcDeleteUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type RpcDeleteUserResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcDeleteUserResponse) Reset()         { *m = RpcDeleteUserResponse{} }
func (m *RpcDeleteUserResponse) String() string { return proto.CompactTextString(m) }
func (*RpcDeleteUserResponse) ProtoMessage()    {}
func (*RpcDeleteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_874b4b11a4ddc7c4, []int{5}
}

func (m *RpcDeleteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcDeleteUserResponse.Unmarshal(m, b)
}
func (m *RpcDeleteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcDeleteUserResponse.Marshal(b, m, deterministic)
}
func (m *RpcDeleteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcDeleteUserResponse.Merge(m, src)
}
func (m *RpcDeleteUserResponse) XXX_Size() int {
	return xxx_messageInfo_RpcDeleteUserResponse.Size(m)
}
func (m *RpcDeleteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcDeleteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RpcDeleteUserResponse proto.InternalMessageInfo

func (m *RpcDeleteUserResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

// ModifyUserInfo
type RpcModifyUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	UserDirectoryId      string   `protobuf:"bytes,2,opt,name=userDirectoryId,proto3" json:"userDirectoryId,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Locked               string   `protobuf:"bytes,4,opt,name=locked,proto3" json:"locked,omitempty"`
	Closed               string   `protobuf:"bytes,5,opt,name=closed,proto3" json:"closed,omitempty"`
	EmployeeId           string   `protobuf:"bytes,6,opt,name=employeeId,proto3" json:"employeeId,omitempty"`
	GroupId              string   `protobuf:"bytes,7,opt,name=groupId,proto3" json:"groupId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcModifyUserRequest) Reset()         { *m = RpcModifyUserRequest{} }
func (m *RpcModifyUserRequest) String() string { return proto.CompactTextString(m) }
func (*RpcModifyUserRequest) ProtoMessage()    {}
func (*RpcModifyUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_874b4b11a4ddc7c4, []int{6}
}

func (m *RpcModifyUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcModifyUserRequest.Unmarshal(m, b)
}
func (m *RpcModifyUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcModifyUserRequest.Marshal(b, m, deterministic)
}
func (m *RpcModifyUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcModifyUserRequest.Merge(m, src)
}
func (m *RpcModifyUserRequest) XXX_Size() int {
	return xxx_messageInfo_RpcModifyUserRequest.Size(m)
}
func (m *RpcModifyUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcModifyUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RpcModifyUserRequest proto.InternalMessageInfo

func (m *RpcModifyUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RpcModifyUserRequest) GetUserDirectoryId() string {
	if m != nil {
		return m.UserDirectoryId
	}
	return ""
}

func (m *RpcModifyUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RpcModifyUserRequest) GetLocked() string {
	if m != nil {
		return m.Locked
	}
	return ""
}

func (m *RpcModifyUserRequest) GetClosed() string {
	if m != nil {
		return m.Closed
	}
	return ""
}

func (m *RpcModifyUserRequest) GetEmployeeId() string {
	if m != nil {
		return m.EmployeeId
	}
	return ""
}

func (m *RpcModifyUserRequest) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

type RpcModifyUserResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcModifyUserResponse) Reset()         { *m = RpcModifyUserResponse{} }
func (m *RpcModifyUserResponse) String() string { return proto.CompactTextString(m) }
func (*RpcModifyUserResponse) ProtoMessage()    {}
func (*RpcModifyUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_874b4b11a4ddc7c4, []int{7}
}

func (m *RpcModifyUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcModifyUserResponse.Unmarshal(m, b)
}
func (m *RpcModifyUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcModifyUserResponse.Marshal(b, m, deterministic)
}
func (m *RpcModifyUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcModifyUserResponse.Merge(m, src)
}
func (m *RpcModifyUserResponse) XXX_Size() int {
	return xxx_messageInfo_RpcModifyUserResponse.Size(m)
}
func (m *RpcModifyUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcModifyUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RpcModifyUserResponse proto.InternalMessageInfo

func (m *RpcModifyUserResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

// ModifyUserPassword
type RpcModifyUserPasswordRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	OldPassword          string   `protobuf:"bytes,2,opt,name=oldPassword,proto3" json:"oldPassword,omitempty"`
	NewPassword          string   `protobuf:"bytes,3,opt,name=newPassword,proto3" json:"newPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcModifyUserPasswordRequest) Reset()         { *m = RpcModifyUserPasswordRequest{} }
func (m *RpcModifyUserPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*RpcModifyUserPasswordRequest) ProtoMessage()    {}
func (*RpcModifyUserPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_874b4b11a4ddc7c4, []int{8}
}

func (m *RpcModifyUserPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcModifyUserPasswordRequest.Unmarshal(m, b)
}
func (m *RpcModifyUserPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcModifyUserPasswordRequest.Marshal(b, m, deterministic)
}
func (m *RpcModifyUserPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcModifyUserPasswordRequest.Merge(m, src)
}
func (m *RpcModifyUserPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_RpcModifyUserPasswordRequest.Size(m)
}
func (m *RpcModifyUserPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcModifyUserPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RpcModifyUserPasswordRequest proto.InternalMessageInfo

func (m *RpcModifyUserPasswordRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RpcModifyUserPasswordRequest) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *RpcModifyUserPasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type RpcModifyUserPasswordResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcModifyUserPasswordResponse) Reset()         { *m = RpcModifyUserPasswordResponse{} }
func (m *RpcModifyUserPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*RpcModifyUserPasswordResponse) ProtoMessage()    {}
func (*RpcModifyUserPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_874b4b11a4ddc7c4, []int{9}
}

func (m *RpcModifyUserPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcModifyUserPasswordResponse.Unmarshal(m, b)
}
func (m *RpcModifyUserPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcModifyUserPasswordResponse.Marshal(b, m, deterministic)
}
func (m *RpcModifyUserPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcModifyUserPasswordResponse.Merge(m, src)
}
func (m *RpcModifyUserPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_RpcModifyUserPasswordResponse.Size(m)
}
func (m *RpcModifyUserPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcModifyUserPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RpcModifyUserPasswordResponse proto.InternalMessageInfo

func (m *RpcModifyUserPasswordResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

// GetUserById
type RpcGetUserByIdRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcGetUserByIdRequest) Reset()         { *m = RpcGetUserByIdRequest{} }
func (m *RpcGetUserByIdRequest) String() string { return proto.CompactTextString(m) }
func (*RpcGetUserByIdRequest) ProtoMessage()    {}
func (*RpcGetUserByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_874b4b11a4ddc7c4, []int{10}
}

func (m *RpcGetUserByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcGetUserByIdRequest.Unmarshal(m, b)
}
func (m *RpcGetUserByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcGetUserByIdRequest.Marshal(b, m, deterministic)
}
func (m *RpcGetUserByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcGetUserByIdRequest.Merge(m, src)
}
func (m *RpcGetUserByIdRequest) XXX_Size() int {
	return xxx_messageInfo_RpcGetUserByIdRequest.Size(m)
}
func (m *RpcGetUserByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcGetUserByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RpcGetUserByIdRequest proto.InternalMessageInfo

func (m *RpcGetUserByIdRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type RpcGetUserByIdResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	UserDirectoryId      string   `protobuf:"bytes,2,opt,name=userDirectoryId,proto3" json:"userDirectoryId,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Locked               string   `protobuf:"bytes,4,opt,name=locked,proto3" json:"locked,omitempty"`
	Closed               string   `protobuf:"bytes,5,opt,name=closed,proto3" json:"closed,omitempty"`
	EmployeeId           string   `protobuf:"bytes,6,opt,name=employeeId,proto3" json:"employeeId,omitempty"`
	GroupId              string   `protobuf:"bytes,7,opt,name=groupId,proto3" json:"groupId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcGetUserByIdResponse) Reset()         { *m = RpcGetUserByIdResponse{} }
func (m *RpcGetUserByIdResponse) String() string { return proto.CompactTextString(m) }
func (*RpcGetUserByIdResponse) ProtoMessage()    {}
func (*RpcGetUserByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_874b4b11a4ddc7c4, []int{11}
}

func (m *RpcGetUserByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcGetUserByIdResponse.Unmarshal(m, b)
}
func (m *RpcGetUserByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcGetUserByIdResponse.Marshal(b, m, deterministic)
}
func (m *RpcGetUserByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcGetUserByIdResponse.Merge(m, src)
}
func (m *RpcGetUserByIdResponse) XXX_Size() int {
	return xxx_messageInfo_RpcGetUserByIdResponse.Size(m)
}
func (m *RpcGetUserByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcGetUserByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RpcGetUserByIdResponse proto.InternalMessageInfo

func (m *RpcGetUserByIdResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RpcGetUserByIdResponse) GetUserDirectoryId() string {
	if m != nil {
		return m.UserDirectoryId
	}
	return ""
}

func (m *RpcGetUserByIdResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RpcGetUserByIdResponse) GetLocked() string {
	if m != nil {
		return m.Locked
	}
	return ""
}

func (m *RpcGetUserByIdResponse) GetClosed() string {
	if m != nil {
		return m.Closed
	}
	return ""
}

func (m *RpcGetUserByIdResponse) GetEmployeeId() string {
	if m != nil {
		return m.EmployeeId
	}
	return ""
}

func (m *RpcGetUserByIdResponse) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

// GetUsers
type RpcGetUsersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcGetUsersRequest) Reset()         { *m = RpcGetUsersRequest{} }
func (m *RpcGetUsersRequest) String() string { return proto.CompactTextString(m) }
func (*RpcGetUsersRequest) ProtoMessage()    {}
func (*RpcGetUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_874b4b11a4ddc7c4, []int{12}
}

func (m *RpcGetUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcGetUsersRequest.Unmarshal(m, b)
}
func (m *RpcGetUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcGetUsersRequest.Marshal(b, m, deterministic)
}
func (m *RpcGetUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcGetUsersRequest.Merge(m, src)
}
func (m *RpcGetUsersRequest) XXX_Size() int {
	return xxx_messageInfo_RpcGetUsersRequest.Size(m)
}
func (m *RpcGetUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcGetUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RpcGetUsersRequest proto.InternalMessageInfo

type RpcGetUsersResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcGetUsersResponse) Reset()         { *m = RpcGetUsersResponse{} }
func (m *RpcGetUsersResponse) String() string { return proto.CompactTextString(m) }
func (*RpcGetUsersResponse) ProtoMessage()    {}
func (*RpcGetUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_874b4b11a4ddc7c4, []int{13}
}

func (m *RpcGetUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcGetUsersResponse.Unmarshal(m, b)
}
func (m *RpcGetUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcGetUsersResponse.Marshal(b, m, deterministic)
}
func (m *RpcGetUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcGetUsersResponse.Merge(m, src)
}
func (m *RpcGetUsersResponse) XXX_Size() int {
	return xxx_messageInfo_RpcGetUsersResponse.Size(m)
}
func (m *RpcGetUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcGetUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RpcGetUsersResponse proto.InternalMessageInfo

func (m *RpcGetUsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type User struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	UserDirectoryId      string   `protobuf:"bytes,2,opt,name=userDirectoryId,proto3" json:"userDirectoryId,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Locked               string   `protobuf:"bytes,4,opt,name=locked,proto3" json:"locked,omitempty"`
	Closed               string   `protobuf:"bytes,5,opt,name=closed,proto3" json:"closed,omitempty"`
	EmployeeId           string   `protobuf:"bytes,6,opt,name=employeeId,proto3" json:"employeeId,omitempty"`
	GroupId              string   `protobuf:"bytes,7,opt,name=groupId,proto3" json:"groupId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_874b4b11a4ddc7c4, []int{14}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *User) GetUserDirectoryId() string {
	if m != nil {
		return m.UserDirectoryId
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetLocked() string {
	if m != nil {
		return m.Locked
	}
	return ""
}

func (m *User) GetClosed() string {
	if m != nil {
		return m.Closed
	}
	return ""
}

func (m *User) GetEmployeeId() string {
	if m != nil {
		return m.EmployeeId
	}
	return ""
}

func (m *User) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func init() {
	proto.RegisterType((*RpcAuthUserRequest)(nil), "userService.RpcAuthUserRequest")
	proto.RegisterType((*RpcAuthUserResponse)(nil), "userService.RpcAuthUserResponse")
	proto.RegisterType((*RpcCreateUserRequest)(nil), "userService.RpcCreateUserRequest")
	proto.RegisterType((*RpcCreateUserResponse)(nil), "userService.RpcCreateUserResponse")
	proto.RegisterType((*RpcDeleteUserRequest)(nil), "userService.RpcDeleteUserRequest")
	proto.RegisterType((*RpcDeleteUserResponse)(nil), "userService.RpcDeleteUserResponse")
	proto.RegisterType((*RpcModifyUserRequest)(nil), "userService.RpcModifyUserRequest")
	proto.RegisterType((*RpcModifyUserResponse)(nil), "userService.RpcModifyUserResponse")
	proto.RegisterType((*RpcModifyUserPasswordRequest)(nil), "userService.RpcModifyUserPasswordRequest")
	proto.RegisterType((*RpcModifyUserPasswordResponse)(nil), "userService.RpcModifyUserPasswordResponse")
	proto.RegisterType((*RpcGetUserByIdRequest)(nil), "userService.RpcGetUserByIdRequest")
	proto.RegisterType((*RpcGetUserByIdResponse)(nil), "userService.RpcGetUserByIdResponse")
	proto.RegisterType((*RpcGetUsersRequest)(nil), "userService.RpcGetUsersRequest")
	proto.RegisterType((*RpcGetUsersResponse)(nil), "userService.RpcGetUsersResponse")
	proto.RegisterType((*User)(nil), "userService.User")
}

func init() { proto.RegisterFile("userService.proto", fileDescriptor_874b4b11a4ddc7c4) }

var fileDescriptor_874b4b11a4ddc7c4 = []byte{
	// 560 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x56, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x8e, 0x49, 0x93, 0xb6, 0x63, 0x15, 0xd4, 0xa5, 0x44, 0x96, 0x55, 0x20, 0x2c, 0x48, 0x04,
	0x0e, 0x41, 0x2a, 0x07, 0x6e, 0x48, 0x40, 0x25, 0x64, 0x21, 0xa4, 0x62, 0xa8, 0x40, 0xe2, 0x14,
	0xec, 0x81, 0x46, 0x75, 0xb3, 0x66, 0xd7, 0xa6, 0x0a, 0x2f, 0xc1, 0x9b, 0xf0, 0x28, 0x3c, 0x02,
	0xe2, 0x51, 0x90, 0xd7, 0xeb, 0x9f, 0xdd, 0x25, 0x71, 0x4f, 0x1c, 0x7a, 0x9c, 0xd9, 0x6f, 0x67,
	0xe6, 0xfb, 0xb2, 0xf3, 0xc5, 0xb0, 0x9b, 0x0b, 0xe4, 0x6f, 0x91, 0x7f, 0x9b, 0x47, 0x38, 0x4d,
	0x39, 0xcb, 0x18, 0x71, 0x5b, 0x29, 0xca, 0x81, 0x84, 0x69, 0xf4, 0x2c, 0xcf, 0x4e, 0x8e, 0x05,
	0xf2, 0x10, 0xbf, 0xe6, 0x28, 0x32, 0x72, 0x0f, 0x76, 0x0a, 0xd0, 0xe1, 0x9c, 0x63, 0x94, 0x31,
	0xbe, 0xf4, 0x9c, 0xb1, 0x33, 0xd9, 0x0e, 0xf5, 0x24, 0xf1, 0x61, 0xab, 0x48, 0x2c, 0x66, 0x67,
	0xe8, 0x5d, 0x91, 0x80, 0x3a, 0x2e, 0xce, 0xd2, 0x99, 0x10, 0xe7, 0x8c, 0xc7, 0x5e, 0xbf, 0x3c,
	0xab, 0x62, 0xfa, 0x0a, 0xae, 0x6b, 0x3d, 0x45, 0xca, 0x16, 0x02, 0xc9, 0x08, 0x86, 0x1c, 0x45,
	0x9e, 0x64, 0xb2, 0xdb, 0x56, 0xa8, 0x22, 0xb2, 0x0f, 0xdb, 0xb3, 0x3c, 0x3b, 0x79, 0xc7, 0x4e,
	0x71, 0xa1, 0xfa, 0x34, 0x09, 0xfa, 0xd3, 0x81, 0xbd, 0x30, 0x8d, 0x5e, 0x70, 0x9c, 0x65, 0xd8,
	0xe6, 0x30, 0x82, 0x61, 0x31, 0x4d, 0x10, 0xab, 0xe1, 0x55, 0x44, 0x26, 0x70, 0x4d, 0xa3, 0x11,
	0xc4, 0xaa, 0xa8, 0x99, 0xd6, 0xf8, 0xf5, 0x0d, 0x7e, 0xb7, 0x00, 0xf0, 0x2c, 0x4d, 0xd8, 0x12,
	0x31, 0x88, 0xbd, 0x0d, 0x79, 0xda, 0xca, 0x10, 0x0f, 0x36, 0xbf, 0x70, 0x96, 0xa7, 0x41, 0xec,
	0x0d, 0xe4, 0x61, 0x15, 0xd2, 0x47, 0x70, 0xc3, 0x98, 0x77, 0x3d, 0x7f, 0x3a, 0x95, 0x04, 0x0f,
	0x31, 0xc1, 0x0b, 0x11, 0x54, 0x0d, 0xda, 0xf8, 0x8e, 0x06, 0xbf, 0x4b, 0x09, 0x5f, 0xb3, 0x78,
	0xfe, 0x79, 0xf9, 0xff, 0x24, 0x1c, 0xc1, 0x30, 0x61, 0xd1, 0x29, 0x56, 0xf2, 0xa9, 0xa8, 0xc8,
	0x47, 0x09, 0x13, 0x58, 0x29, 0xa7, 0x22, 0x43, 0xf2, 0xe1, 0x3a, 0xc9, 0x37, 0xff, 0x25, 0x79,
	0x9b, 0x5f, 0x87, 0x22, 0xdf, 0x61, 0x5f, 0xbb, 0x70, 0xa4, 0x9e, 0x6e, 0x97, 0x30, 0x63, 0x70,
	0x59, 0x12, 0x57, 0x68, 0x25, 0x4a, 0x3b, 0x55, 0x20, 0x16, 0x78, 0x7e, 0xa4, 0xaf, 0x46, 0x3b,
	0x45, 0x9f, 0xc0, 0xcd, 0x15, 0xbd, 0x3b, 0x86, 0x2e, 0x59, 0xbe, 0xc4, 0xac, 0xb8, 0xf5, 0x7c,
	0x19, 0x74, 0x4d, 0x4b, 0xff, 0x38, 0x30, 0x32, 0x6f, 0x34, 0x3d, 0x2e, 0xc5, 0x2f, 0xbf, 0x27,
	0xed, 0x4d, 0x31, 0x14, 0x4a, 0x10, 0xfa, 0x54, 0x1a, 0x50, 0x93, 0x55, 0xa4, 0xef, 0xc3, 0xa0,
	0x18, 0x51, 0x78, 0xce, 0xb8, 0x3f, 0x71, 0x0f, 0x76, 0xa7, 0x6d, 0xef, 0x94, 0xef, 0xa6, 0x3c,
	0xa7, 0xbf, 0x1c, 0xd8, 0x28, 0xe2, 0xcb, 0x22, 0xd3, 0xc1, 0x8f, 0x01, 0xb8, 0xc7, 0x0d, 0x59,
	0xf2, 0x06, 0xdc, 0x96, 0x43, 0x93, 0xdb, 0x9a, 0x12, 0xf6, 0xff, 0x85, 0xdf, 0x05, 0xa0, 0x3d,
	0xf2, 0x1e, 0x76, 0x34, 0xdb, 0x23, 0x77, 0xcc, 0x3b, 0x96, 0x85, 0xfb, 0xdd, 0x90, 0xba, 0x70,
	0x63, 0x77, 0x76, 0x61, 0xcb, 0x3a, 0xfd, 0x6e, 0x08, 0xed, 0x91, 0x0f, 0xb2, 0x70, 0xb3, 0x88,
	0x76, 0x61, 0xcb, 0x31, 0x7d, 0xba, 0x0e, 0x52, 0x3e, 0x33, 0xda, 0x23, 0xa9, 0xe1, 0x47, 0xb5,
	0x3b, 0x3c, 0x58, 0x7d, 0xdd, 0xb0, 0x20, 0xff, 0xe1, 0x45, 0xa0, 0x75, 0xc7, 0x8f, 0x70, 0x55,
	0xdf, 0x74, 0x62, 0x4d, 0x6a, 0x1b, 0x87, 0x7f, 0x77, 0x2d, 0xa6, 0x2e, 0x1e, 0xca, 0xd7, 0x52,
	0xad, 0x93, 0xfd, 0x5a, 0x8c, 0xf5, 0xf3, 0xc7, 0xab, 0x01, 0x55, 0xcd, 0x4f, 0x43, 0xf9, 0xad,
	0xf2, 0xf8, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x60, 0x84, 0x09, 0x68, 0xc0, 0x08, 0x00, 0x00,
}
